imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

# FosUser Configuration
fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    Btask\UserBundle\Entity\User

    # Define the parameters for sended email about users from the system
    from_email:
        address:        %mailer_sender_email%
        sender_name:    %mailer_sender_title%

    # Override the UserManager from FOSUserBundle
    service:
        user_manager: btask_user.onsite_user_manager
        mailer: fos_user.mailer.twig_swift

    # Configuration for the profile
    profile:
        # Override the profile template from FOSUserBundle
        form:
            type: btask_user_profile

    # Configuration for the registration
    registration:
        # Override the registration template from FOSUserBundle
        form:
            type: btask_user_registration

        confirmation:
            enabled:    true
            # Define the email template for the registration confirmation
            template: BtaskUserBundle:Registration:email.html.twig

    # Configuration for the password resetting
    resetting:
        token_ttl: 86400
        email:
            # Define the email template for the password resetting
            template: BtaskUserBundle:Resetting:email.html.twig
