security:
    encoders:
        "FOS\UserBundle\Model\UserInterface": sha512

    role_hierarchy:
        ROLE_USER: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Main firewall
        main:
            pattern: ^/
            form_login:
                provider:    fos_userbundle
                remember_me: true
                # Redirect on the board when login success
                always_use_default_target_path: true
                default_target_path: /board
            remember_me:
                key:         %secret%
            anonymous:       true
            logout:          true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/board, role: IS_AUTHENTICATED_FULLY }
