security:
    encoders:
        "FOS\UserBundle\Model\UserInterface": sha512


    role_hierarchy:
        ROLE_USER:       ROLE_GUEST

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # Firewall for inscription and login page
        login:
            pattern:   ^/(login$|register|resetting)
            anonymous: true

        # Main firewall
        main:
            pattern: ^/
            form_login:
                provider:    fos_userbundle
                remember_me: true
            remember_me:
                key:         %secret%
            anonymous:       true
            logout:          true

    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, role: IS_AUTHENTICATED_FULLY }
