parameters:
#    btask_user.example.class: Btask\UserBundle\Example

services:
#    btask_user.example:
#        class: %btask_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
