# General
BtaskBoardBundle_today:
    pattern:  /today
    defaults: { _controller: BtaskBoardBundle:Default:showToday }
    options:
        expose: true

BtaskBoardBundle_board:
    pattern:  /
    defaults: { _controller: BtaskBoardBundle:Default:showBoard }

# Post-it
BtaskBoardBundle_post_it_create:
    pattern:  /post-it/create/
    defaults: { _controller: BtaskBoardBundle:PostIt:createPostIt }
    options:
        expose: true

BtaskBoardBundle_post_it_update:
    pattern:  /post-it/{id}/edit/
    defaults: { _controller: BtaskBoardBundle:PostIt:updatePostIt }
    requirements:
        id: \d+
    options:
        expose: true

BtaskBoardBundle_post_it_delete:
    pattern:  /post-it/{id}/delete/
    defaults: { _controller: BtaskBoardBundle:PostIt:deletePostIt }
    requirements:
        id: \d+
    options:
        expose: true

BtaskBoardBundle_postit_close:
    pattern:  /post-it/{id}/close/
    defaults: { _controller: BtaskBoardBundle:PostIt:closePostIt }
    requirements:
        id: \d+
    options:
        expose: true

BtaskBoardBundle_post_it_show:
    pattern:  /post-it/{id}/
    defaults: { _controller: BtaskBoardBundle:PostIt:showPostIt }
    requirements:
        id: \d+
    options:
        expose: true

BtaskBoardBundle_posts_it_show:
    pattern: /post-it/
    defaults: { _controller: BtaskBoardBundle:PostIt:showPostsIt }
    options:
        expose: true


# Task
BtaskBoardBundle_tasks_by_project_show:
    pattern:  /{project_slug}/tasks/{state}
    defaults: { _controller: BtaskBoardBundle:Task:showTasksByStateAndByProject }
    requirements:
        project_slug: \w+
    requirements:
        state: (overdue|planned|done)
    options:
        expose: true

BtaskBoardBundle_task_udpate:
    pattern:  /task/{id}/edit/
    defaults: { _controller: BtaskBoardBundle:Task:updateTask }
    requirements:
        id: \d+
    options:
        expose: true

BtaskBoardBundle_task_delete:
    pattern:  /task/{id}/delete/
    defaults: { _controller: BtaskBoardBundle:Task:deleteTask }
    requirements:
        id: \d+
    options:
        expose: true

BtaskBoardBundle_tasks_by_state_show:
    pattern:  /tasks/{state}/
    defaults: { _controller: BtaskBoardBundle:Task:showTasksByState }
    requirements:
        state: (overdue|planned|done)
    options:
        expose: true

BtaskBoardBundle_task_close:
    pattern:  /task/{id}/close/
    defaults: { _controller: BtaskBoardBundle:Task:toggleStatusTask, status: false }
    requirements:
        id: \d+
    options:
        expose: true

BtaskBoardBundle_task_open:
    pattern:  /task/{id}/open/
    defaults: { _controller: BtaskBoardBundle:Task:toggleStatusTask, status: true }
    requirements:
        id: \d+
    options:
        expose: true

BtaskBoardBundle_task_show:
    pattern:  /tasks/{id}/
    defaults: { _controller: BtaskBoardBundle:Task:showTask }
    requirements:
        id: \d+
    options:
        expose: true

# Note
BtaskBoardBundle_notes_by_project_show:
    pattern:  /{project_slug}/notes/
    defaults: { _controller: BtaskBoardBundle:Note:showNotesByProject }
    requirements:
        project_slug: \w+
    options:
        expose: true

BtaskBoardBundle_note_show:
    pattern:  /notes/{id}/
    defaults: { _controller: BtaskBoardBundle:Note:showNote }
    requirements:
        id: \d+
    options:
        expose: true

BtaskBoardBundle_notes_show:
    pattern:  /notes/
    defaults: { _controller: BtaskBoardBundle:Note:showNotes }
    requirements:
        id: \d+
    options:
        expose: true

BtaskBoardBundle_note_update:
    pattern:  /note/{id}/edit/
    defaults: { _controller: BtaskBoardBundle:Note:updateNote }
    requirements:
        id: \d+
    options:
        expose: true

BtaskBoardBundle_note_delete:
    pattern:  /note/{id}/delete/
    defaults: { _controller: BtaskBoardBundle:Note:deleteNote }
    requirements:
        id: \d+
    options:
        expose: true

# Project
BtaskBoardBundle_project_participants_show:
    pattern:  /projects/{id}/users/
    defaults: { _controller: BtaskBoardBundle:Project:showParticipants }
    requirements:
        id: \d+
    options:
        expose: true

BtaskBoardBundle_project_show:
    pattern:  /projects/{id}
    defaults: { _controller: BtaskBoardBundle:Project:showProject }
    requirements:
        id: \d+
    options:
        expose: true

BtaskBoardBundle_projects_by_workgroup_show:
    pattern:  /{workgroup_slug}/projects/
    defaults: { _controller: BtaskBoardBundle:Project:showProjectsByWorkgroup }
    requirements:
        workgroup_slug: \w+
    options:
        expose: true

BtaskBoardBundle_project_create:
    pattern:  /project/create/
    defaults: { _controller: BtaskBoardBundle:Project:createProject }
    requirements:
        workgroup_slug: \w+
    options:
        expose: true

BtaskBoardBundle_project_update:
    pattern:  /project/{id}/edit/
    defaults: { _controller: BtaskBoardBundle:Project:updateProject }
    requirements:
        id: \d+
    options:
        expose: true

BtaskBoardBundle_project_delete:
    pattern:  /project/{id}/delete/
    defaults: { _controller: BtaskBoardBundle:Project:deleteProject }
    requirements:
        id: \d+
    options:
        expose: true

# Workgroup
BtaskBoardBundle_workgroup_create:
    pattern:  /workgroup/create
    defaults: { _controller: BtaskBoardBundle:Workgroup:createWorkgroup }
    options:
        expose: true

BtaskBoardBundle_workgroup_update:
    pattern:  /workgroup/{id}/edit
    defaults: { _controller: BtaskBoardBundle:Workgroup:updateWorkgroup }
    requirements:
        id: \d+
    options:
        expose: true

BtaskBoardBundle_workgroup_delete:
    pattern:  /workgroup/{id}/delete
    defaults: { _controller: BtaskBoardBundle:Workgroup:deleteWorkgroup }
    requirements:
        id: \d+
    options:
        expose: true

BtaskBoardBundle_workgroup_show:
    pattern:  /workgroups/{id}
    defaults: { _controller: BtaskBoardBundle:Workgroup:showWorkgroup }
    requirements:
        id: \d+
    options:
        expose: true

BtaskBoardBundle_workgroups_show:
    pattern:  /workgroups/
    defaults: { _controller: BtaskBoardBundle:Workgroup:showWorkgroups }
    options:
        expose: true

BtaskBoardBundle_project:
    pattern:  /{project_slug}
    defaults: { _controller: BtaskBoardBundle:Default:showProject }
    requirements:
        project_slug: \w+
    options:
        expose: true
