BtaskBoardBundle_today:
    pattern:  /today
    defaults: { _controller: BtaskBoardBundle:Default:today }

BtaskBoardBundle_board:
    pattern:  /
    defaults: { _controller: BtaskBoardBundle:Default:showBoard }

BtaskBoardBundle_post_it_add:
    pattern:  /post-it/add/
    defaults: { _controller: BtaskBoardBundle:Default:newPostIt }

BtaskBoardBundle_post_it_edit:
    pattern:  /post-it/{id}/edit/
    defaults: { _controller: BtaskBoardBundle:Default:editPostIt }

BtaskBoardBundle_postit:
    pattern: /post-it/
    defaults: { _controller: BtaskBoardBundle:Default:showPostIt }

BtaskBoardBundle_task_edit:
    pattern:  /task/{id}/edit
    defaults: { _controller: BtaskBoardBundle:Default:editTask }
    requirements:
        id: \d+

BtaskBoardBundle_tasks_by_state:
    pattern:  /tasks/{state}/
    defaults: { _controller: BtaskBoardBundle:Default:showTasksByState }
    requirements:
        status: (overdue|planned|done)

BtaskBoardBundle_task_close:
    pattern:  /task/{id}/close
    defaults: { _controller: BtaskBoardBundle:Default:toggleStatusTask, status: false }
    requirements:
        id: \d+

BtaskBoardBundle_task_open:
    pattern:  /task/{id}/open
    defaults: { _controller: BtaskBoardBundle:Default:toggleStatusTask, status: true }
    requirements:
        id: \d+

BtaskBoardBundle_note_edit:
    pattern:  /note/{id}/edit
    defaults: { _controller: BtaskBoardBundle:Default:editNote }
    requirements:
        id: \d+

BtaskBoardBundle_workgroups:
    pattern:  /workgroups
    defaults: { _controller: BtaskBoardBundle:Default:showWorkgroups }
