# General
BtaskBoardBundle_today:
    pattern:  /today
    defaults: { _controller: BtaskBoardBundle:Default:today }

BtaskBoardBundle_board:
    pattern:  /
    defaults: { _controller: BtaskBoardBundle:Default:showBoard }


# Post-it
BtaskBoardBundle_post_it_create:
    pattern:  /post-it/add/
    defaults: { _controller: BtaskBoardBundle:PostIt:createPostIt }

BtaskBoardBundle_post_it_update:
    pattern:  /post-it/{id}/edit/
    defaults: { _controller: BtaskBoardBundle:PostIt:updatePostIt }

BtaskBoardBundle_post_it_show:
    pattern: /post-it/
    defaults: { _controller: BtaskBoardBundle:PostIt:showPostIt }
    options:
        expose: true


# Task
BtaskBoardBundle_task_udpate:
    pattern:  /task/{id}/edit
    defaults: { _controller: BtaskBoardBundle:Task:editTask }
    requirements:
        id: \d+
    options:
        expose: true

BtaskBoardBundle_tasks_by_state_show:
    pattern:  /tasks/{state}/
    defaults: { _controller: BtaskBoardBundle:Task:showTasksByState }
    requirements:
        state: (overdue|planned|done)
    options:
        expose: true

BtaskBoardBundle_task_close:
    pattern:  /task/{id}/close
    defaults: { _controller: BtaskBoardBundle:Task:toggleStatusTask, status: false }
    requirements:
        id: \d+

BtaskBoardBundle_task_open:
    pattern:  /task/{id}/open
    defaults: { _controller: BtaskBoardBundle:Task:toggleStatusTask, status: true }
    requirements:
        id: \d+


# Note
BtaskBoardBundle_note_edit:
    pattern:  /note/{id}/edit
    defaults: { _controller: BtaskBoardBundle:Default:editNote }
    requirements:
        id: \d+


# Workgroup
BtaskBoardBundle_workgroup_create:
    pattern:  /workgroup/add
    defaults: { _controller: BtaskBoardBundle:Workgroup:createWorkgroup }
    options:
        expose: true

BtaskBoardBundle_workgroup_update:
    pattern:  /workgroup/{id}/edit
    defaults: { _controller: BtaskBoardBundle:Workgroup:updateWorkgroup }
    requirements:
        id: \d+
    options:
        expose: true

BtaskBoardBundle_workgroup_delete:
    pattern:  /workgroup/{id}/delete
    defaults: { _controller: BtaskBoardBundle:Workgroup:deleteWorkgroup }
    requirements:
        id: \d+
    options:
        expose: true

BtaskBoardBundle_workgroup_show:
    pattern:  /workgroups/{id}
    defaults: { _controller: BtaskBoardBundle:Workgroup:showWorkgroup }
    requirements:
        id: \d+
    options:
        expose: true

BtaskBoardBundle_workgroups_show:
    pattern:  /workgroups
    defaults: { _controller: BtaskBoardBundle:Workgroup:showWorkgroups }
    options:
        expose: true

# Project
BtaskBoardBundle_projects_by_workgroup_show:
    pattern:  /{workgroup_slug}/projects/
    defaults: { _controller: BtaskBoardBundle:Project:showProjectsByWorkgroup }
    requirements:
        id: \w+
    options:
        expose: true
